### ISSUE TITLE
Уязвимость

### ISSUE THREAD

**Issue by KasimirKoch** [OpenBuilders/notcoin-contract#1]
Ради интереса дал ссылку боту ИИ:
После изучения кода по предоставленной ссылке на GitHub, я обнаружил следующую уязвимость, которая может быть использована для атаки:

Описание уязвимости: В функции transfer контракта Notcoin код позволяет передавать токены на адреса без проверки, является ли адрес получателя контрактным адресом или адресом внешнего владельца. Этот недостаток проверки открывает возможность для атаки методом повторного входа (re-entrancy attack).

Пошаговая эксплуатация:

Атакующий развертывает зловредный контракт с функцией обратного вызова, которая вызывает функцию transfer контракта Notcoin после получения токенов.
Атакующий инициирует передачу токенов на адрес зловредного контракта, используя функцию transfer контракта Notcoin.
Функция обратного вызова зловредного контракта срабатывает при входящем переводе и вызывает функцию transfer контракта Notcoin для повторной передачи токенов атакующему, прежде чем обновить баланс атакующего.
Поскольку контракт Notcoin не учитывает повторный вход, атакующий может выкачать токены из контракта Notcoin, рекурсивно вызывая функцию transfer внутри функции обратного вызова зловредного контракта.
Эта уязвимость может привести к значительной потере токенов из контракта Notcoin, поскольку атакующий может выкачать баланс токенов контракта, повторно запрашивая переводы в рамках одной транзакции.

Рекомендация: Для устранения этой уязвимости критически важно включить проверку в функции transfer, чтобы предотвратить передачу токенов на контрактные адреса. Один из способов достижения этого - использование функции address.isContract для проверки адреса получателя перед выполнением передачи. Если адрес получателя идентифицируется как контракт, передача должна быть отклонена, чтобы предотвратить атаки методом повторного входа.

Пожалуйста, убедитесь, что эта исправление будет внедрено, чтобы защитить контракт Notcoin от потенциальных атак.

**Comment by recfrf44** [comment]
плотвинов мамкин програмист и клоун

**Comment by sinopsis08** [comment]
волотька может писать только бывшей и мемуары под гитару

**Comment by tresting** [comment]
ко мне плотва! плова когда листинг, когда листинг плотва, игого фырфыр фыр
